### ISSUE TITLE
POS Surcharge

### ISSUE THREAD

**Issue by somvirbhatti** [bizswoop/Point-of-Sale-POS-WooCommerce#6]
Hi, 
We are developing a website in Wordpress for public school uniform shop. 
Is there a capability of adding Credit card surcharge fee in the payments ?
For example Stripe charges 1.75% + 0.30 cent as transaction fee but current POS doesn't provide any configuration to add fee or surcharges.
This would be certainly be a big feature to cover.

Also not sure , do you intend to create a Till sheet capability which shows the total daily sales at the end of day with payment gateway summaries.

**Comment by SupportBizSwoop** [comment]
Thanks for reaching out and sharing the use cases for your website. 

I'd be happy to provide feedback on each item. 

Item 1: Fee on the POS. 
We do support adding fees on an order. Instead of supporting a basic fee button with a value. We developed the Custom Product feature. We'd recommend the Custom Product Feature used for Fees. This solution allows you to customize the name of the fee for customers, provide the ability to define quantity and a fee value, as shown on this quick video: https://www.loom.com/share/e18256079d28473abad9d829d4472b0c

For any type of transaction fee in addition automatically, unfortunately, we don't have any plans to add additional or transaction fees to payment gateways. This would be a requirement on the Payment Processor to allow their accounts to up charge a fee for using the gateway and add fees on the transaction to customers. 

Item 2: Point of Sale Reports
Right now, the POS provides reports on the Cashier level, Order Type and Sales by Payment method which includes the POS payment options: Cash, Stripe Other Payments and etc. These are the Core Reports provided, as shown on this quick video: https://www.loom.com/share/eeac417f57f34f3b893fb61f2e810ed7

From our experience, we have found that each business has a slightly different reporting requirement and Till sheet requirement based upon their industry and country of origin. Some businesses use only the POS Core Reports, other businesses pull the meta data and perform their own external reporting, while other businesses use Third Party tools. Hopefully one of these options will fulfill your reporting requirements for the Till sheet capability at this time. 

If not, please provide us more details on what you require and country of origin for reports. We are always looking to improve the reporting functionality to better generate data businesses require while using the POS product.

**Comment by somvirbhatti** [comment]
Thanks for your response. Much appreciated
